### ISSUE TITLE
High severity outated axios library

### ISSUE THREAD

**Issue by hugodecasta** [funkyremi/deepl#4]
Installing the deepl library raises `2 high severity vulnerabilities` because of the known axios < 0.21.1 version vulnerability

```
axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  deepl  *
  Depends on vulnerable versions of axios
  node_modules/deepl

2 high severity vulnerabilities
```

A pull request is currently pending with no conflict and thus needs to be merged https://github.com/funkyremi/deepl/pull/3

**Comment by funkyremi** [comment]
You're right, sorry I missed this one.
I just published version 1.0.5. 
Enjoy
