### ISSUE TITLE
Error: document translating

### ISSUE THREAD

**Issue by e2045** [funkyremi/deepl#6]
Hello,

I tried to translate a document, but this error occured after I updated a new version. 

> c:\Users\myUser\Tool\listFiles.js:47
>     translate({
>     ^
> 
> TypeError: translate is not a function
>     at Object.<anonymous> (c:\Users\myUser\Tool\listFiles.js:47:5)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47

This is error with version 1.0.4:

> Error: Request failed with status code 400
>     at createError (c:\Users\myUser\Tool\node_modules\axios\lib\core\createError.js:16:15)
>     at settle (c:\Users\myUser\Tool\node_modules\axios\lib\core\settle.js:17:12)
>     at IncomingMessage.handleStreamEnd (c:\Users\myUser\Tool\node_modules\axios\lib\adapters\http.js:236:11)
>     at IncomingMessage.emit (events.js:327:22)
>     at endReadableNT (internal/streams/readable.js:1327:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)

This is my code: 

```
    const testDoc = 'C:\\Users\\myUser\\Doku\\testMD.docx'
    const translate = require("deepl");

    translate({
        target_lang: 'DE',
        auth_key: 'myKey',
        file: testDoc,
    }).then(result => {
        console.log(result.data);
    }).catch(error => {
        console.error(error)
    });
```

Could you please help me to handle this issue?

Thank you in advance.

**Comment by funkyremi** [comment]
Hi, this should be fixed in the new release 1.0.6.
Sorry for the inconvenience and thanks to @hugodecasta for pull request #5
